/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface LiquidationEngineInterface extends ethers.utils.Interface {
  functions: {
    "accountingEngine()": FunctionFragment;
    "authorizedAccounts(address)": FunctionFragment;
    "collateralTypes(bytes32)": FunctionFragment;
    "globalDebtRequiredForActiveAuctions()": FunctionFragment;
    "globalMaxDebtForActiveAuctions()": FunctionFragment;
    "grantAuthorization(address)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "ledger()": FunctionFragment;
    "liquidatePosition(bytes32,address,address)": FunctionFragment;
    "liquidatonPenalty(bytes32)": FunctionFragment;
    "live()": FunctionFragment;
    "removeDebtFromLiquidation(bytes32,uint256)": FunctionFragment;
    "revokeAuthorization(address)": FunctionFragment;
    "shutdown()": FunctionFragment;
    "updateAccountingEngine(address)": FunctionFragment;
    "updateGlobalMaxDebtForActiveAuctions(uint256)": FunctionFragment;
    "updateLiquidationAuction(bytes32,address)": FunctionFragment;
    "updateLiquidatonPenalty(bytes32,uint256)": FunctionFragment;
    "updateMaxDebtForActiveAuctions(bytes32,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "accountingEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedAccounts",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralTypes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalDebtRequiredForActiveAuctions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "globalMaxDebtForActiveAuctions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantAuthorization",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(functionFragment: "ledger", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "liquidatePosition",
    values: [BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidatonPenalty",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "live", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeDebtFromLiquidation",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAuthorization",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "shutdown", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAccountingEngine",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGlobalMaxDebtForActiveAuctions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLiquidationAuction",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLiquidatonPenalty",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMaxDebtForActiveAuctions",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "accountingEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalDebtRequiredForActiveAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalMaxDebtForActiveAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ledger", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidatePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidatonPenalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "live", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeDebtFromLiquidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "shutdown", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAccountingEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGlobalMaxDebtForActiveAuctions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLiquidationAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLiquidatonPenalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMaxDebtForActiveAuctions",
    data: BytesLike
  ): Result;

  events: {
    "DebtRemoved(bytes32,uint256)": EventFragment;
    "GrantAuthorization(address)": EventFragment;
    "LiquidatePosition(bytes32,uint256,address,uint256,uint256,uint256,address)": EventFragment;
    "RevokeAuthorization(address)": EventFragment;
    "Shutdown()": EventFragment;
    "UpdateParameter(bytes32,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DebtRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GrantAuthorization"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiquidatePosition"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RevokeAuthorization"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Shutdown"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateParameter"): EventFragment;
}

export type DebtRemovedEvent = TypedEvent<
  [string, BigNumber] & { ilk: string; rad: BigNumber }
>;

export type GrantAuthorizationEvent = TypedEvent<
  [string] & { account: string }
>;

export type LiquidatePositionEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, BigNumber, BigNumber, string] & {
    collateralType: string;
    auctionId: BigNumber;
    position: string;
    lockedCollateralToConfiscate: BigNumber;
    normalizedDebtToConfiscate: BigNumber;
    debtConfiscated: BigNumber;
    liquidationAuction: string;
  }
>;

export type RevokeAuthorizationEvent = TypedEvent<
  [string] & { account: string }
>;

export type ShutdownEvent = TypedEvent<[] & {}>;

export type UpdateParameter_bytes32_uint256_Event = TypedEvent<
  [string, BigNumber] & { parameter: string; data: BigNumber }
>;

export type UpdateParameter_bytes32_address_Event = TypedEvent<
  [string, string] & { parameter: string; data: string }
>;

export type UpdateParameter_bytes32_bytes32_uint256_Event = TypedEvent<
  [string, string, BigNumber] & {
    parameter: string;
    collateralType: string;
    data: BigNumber;
  }
>;

export type UpdateParameter_bytes32_bytes32_address_Event = TypedEvent<
  [string, string, string] & {
    parameter: string;
    collateralType: string;
    data: string;
  }
>;

export class LiquidationEngine extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LiquidationEngineInterface;

  functions: {
    accountingEngine(overrides?: CallOverrides): Promise<[string]>;

    authorizedAccounts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    collateralTypes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        liquidationAuction: string;
        liquidatonPenalty: BigNumber;
        maxDebtForActiveAuctions: BigNumber;
        debtRequiredForActiveAuctions: BigNumber;
      }
    >;

    globalDebtRequiredForActiveAuctions(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    globalMaxDebtForActiveAuctions(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    grantAuthorization(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      ledger_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ledger(overrides?: CallOverrides): Promise<[string]>;

    liquidatePosition(
      collateralType: BytesLike,
      position: string,
      keeper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    liquidatonPenalty(
      ilk: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    live(overrides?: CallOverrides): Promise<[BigNumber]>;

    removeDebtFromLiquidation(
      collateralType: BytesLike,
      rad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeAuthorization(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    shutdown(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateAccountingEngine(
      data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateGlobalMaxDebtForActiveAuctions(
      data: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateLiquidationAuction(
      collateralType: BytesLike,
      liquidationAuction: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateLiquidatonPenalty(
      collateralType: BytesLike,
      data: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateMaxDebtForActiveAuctions(
      collateralType: BytesLike,
      data: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  accountingEngine(overrides?: CallOverrides): Promise<string>;

  authorizedAccounts(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  collateralTypes(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber] & {
      liquidationAuction: string;
      liquidatonPenalty: BigNumber;
      maxDebtForActiveAuctions: BigNumber;
      debtRequiredForActiveAuctions: BigNumber;
    }
  >;

  globalDebtRequiredForActiveAuctions(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  globalMaxDebtForActiveAuctions(overrides?: CallOverrides): Promise<BigNumber>;

  grantAuthorization(
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    ledger_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ledger(overrides?: CallOverrides): Promise<string>;

  liquidatePosition(
    collateralType: BytesLike,
    position: string,
    keeper: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  liquidatonPenalty(
    ilk: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  live(overrides?: CallOverrides): Promise<BigNumber>;

  removeDebtFromLiquidation(
    collateralType: BytesLike,
    rad: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeAuthorization(
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  shutdown(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateAccountingEngine(
    data: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateGlobalMaxDebtForActiveAuctions(
    data: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateLiquidationAuction(
    collateralType: BytesLike,
    liquidationAuction: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateLiquidatonPenalty(
    collateralType: BytesLike,
    data: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateMaxDebtForActiveAuctions(
    collateralType: BytesLike,
    data: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    accountingEngine(overrides?: CallOverrides): Promise<string>;

    authorizedAccounts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collateralTypes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        liquidationAuction: string;
        liquidatonPenalty: BigNumber;
        maxDebtForActiveAuctions: BigNumber;
        debtRequiredForActiveAuctions: BigNumber;
      }
    >;

    globalDebtRequiredForActiveAuctions(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    globalMaxDebtForActiveAuctions(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantAuthorization(user: string, overrides?: CallOverrides): Promise<void>;

    initialize(ledger_: string, overrides?: CallOverrides): Promise<void>;

    ledger(overrides?: CallOverrides): Promise<string>;

    liquidatePosition(
      collateralType: BytesLike,
      position: string,
      keeper: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidatonPenalty(
      ilk: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    live(overrides?: CallOverrides): Promise<BigNumber>;

    removeDebtFromLiquidation(
      collateralType: BytesLike,
      rad: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeAuthorization(user: string, overrides?: CallOverrides): Promise<void>;

    shutdown(overrides?: CallOverrides): Promise<void>;

    updateAccountingEngine(
      data: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateGlobalMaxDebtForActiveAuctions(
      data: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateLiquidationAuction(
      collateralType: BytesLike,
      liquidationAuction: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateLiquidatonPenalty(
      collateralType: BytesLike,
      data: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMaxDebtForActiveAuctions(
      collateralType: BytesLike,
      data: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DebtRemoved(bytes32,uint256)"(
      ilk?: BytesLike | null,
      rad?: null
    ): TypedEventFilter<[string, BigNumber], { ilk: string; rad: BigNumber }>;

    DebtRemoved(
      ilk?: BytesLike | null,
      rad?: null
    ): TypedEventFilter<[string, BigNumber], { ilk: string; rad: BigNumber }>;

    "GrantAuthorization(address)"(
      account?: string | null
    ): TypedEventFilter<[string], { account: string }>;

    GrantAuthorization(
      account?: string | null
    ): TypedEventFilter<[string], { account: string }>;

    "LiquidatePosition(bytes32,uint256,address,uint256,uint256,uint256,address)"(
      collateralType?: BytesLike | null,
      auctionId?: BigNumberish | null,
      position?: string | null,
      lockedCollateralToConfiscate?: null,
      normalizedDebtToConfiscate?: null,
      debtConfiscated?: null,
      liquidationAuction?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber, BigNumber, BigNumber, string],
      {
        collateralType: string;
        auctionId: BigNumber;
        position: string;
        lockedCollateralToConfiscate: BigNumber;
        normalizedDebtToConfiscate: BigNumber;
        debtConfiscated: BigNumber;
        liquidationAuction: string;
      }
    >;

    LiquidatePosition(
      collateralType?: BytesLike | null,
      auctionId?: BigNumberish | null,
      position?: string | null,
      lockedCollateralToConfiscate?: null,
      normalizedDebtToConfiscate?: null,
      debtConfiscated?: null,
      liquidationAuction?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber, BigNumber, BigNumber, string],
      {
        collateralType: string;
        auctionId: BigNumber;
        position: string;
        lockedCollateralToConfiscate: BigNumber;
        normalizedDebtToConfiscate: BigNumber;
        debtConfiscated: BigNumber;
        liquidationAuction: string;
      }
    >;

    "RevokeAuthorization(address)"(
      account?: string | null
    ): TypedEventFilter<[string], { account: string }>;

    RevokeAuthorization(
      account?: string | null
    ): TypedEventFilter<[string], { account: string }>;

    "Shutdown()"(): TypedEventFilter<[], {}>;

    Shutdown(): TypedEventFilter<[], {}>;

    "UpdateParameter(bytes32,uint256)"(
      parameter?: BytesLike | null,
      data?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { parameter: string; data: BigNumber }
    >;

    "UpdateParameter(bytes32,address)"(
      parameter?: BytesLike | null,
      data?: null
    ): TypedEventFilter<[string, string], { parameter: string; data: string }>;

    "UpdateParameter(bytes32,bytes32,uint256)"(
      parameter?: BytesLike | null,
      collateralType?: BytesLike | null,
      data?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { parameter: string; collateralType: string; data: BigNumber }
    >;

    "UpdateParameter(bytes32,bytes32,address)"(
      parameter?: BytesLike | null,
      collateralType?: BytesLike | null,
      data?: null
    ): TypedEventFilter<
      [string, string, string],
      { parameter: string; collateralType: string; data: string }
    >;
  };

  estimateGas: {
    accountingEngine(overrides?: CallOverrides): Promise<BigNumber>;

    authorizedAccounts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collateralTypes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    globalDebtRequiredForActiveAuctions(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    globalMaxDebtForActiveAuctions(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantAuthorization(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      ledger_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ledger(overrides?: CallOverrides): Promise<BigNumber>;

    liquidatePosition(
      collateralType: BytesLike,
      position: string,
      keeper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    liquidatonPenalty(
      ilk: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    live(overrides?: CallOverrides): Promise<BigNumber>;

    removeDebtFromLiquidation(
      collateralType: BytesLike,
      rad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeAuthorization(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    shutdown(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateAccountingEngine(
      data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateGlobalMaxDebtForActiveAuctions(
      data: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateLiquidationAuction(
      collateralType: BytesLike,
      liquidationAuction: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateLiquidatonPenalty(
      collateralType: BytesLike,
      data: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateMaxDebtForActiveAuctions(
      collateralType: BytesLike,
      data: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accountingEngine(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    authorizedAccounts(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    collateralTypes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    globalDebtRequiredForActiveAuctions(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    globalMaxDebtForActiveAuctions(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantAuthorization(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      ledger_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ledger(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    liquidatePosition(
      collateralType: BytesLike,
      position: string,
      keeper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    liquidatonPenalty(
      ilk: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    live(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeDebtFromLiquidation(
      collateralType: BytesLike,
      rad: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeAuthorization(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    shutdown(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateAccountingEngine(
      data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateGlobalMaxDebtForActiveAuctions(
      data: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateLiquidationAuction(
      collateralType: BytesLike,
      liquidationAuction: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateLiquidatonPenalty(
      collateralType: BytesLike,
      data: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateMaxDebtForActiveAuctions(
      collateralType: BytesLike,
      data: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
