"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        name: "discountPrice",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
var DiscountCalculator__factory = /** @class */ (function () {
    function DiscountCalculator__factory() {
    }
    DiscountCalculator__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    DiscountCalculator__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    DiscountCalculator__factory.abi = _abi;
    return DiscountCalculator__factory;
}());
exports.DiscountCalculator__factory = DiscountCalculator__factory;
