"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "",
                type: "bytes32"
            },
            {
                internalType: "address",
                name: "",
                type: "address"
            },
            {
                internalType: "int256",
                name: "",
                type: "int256"
            },
        ],
        name: "modifyCollateral",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function"
    },
];
var LedgerLike__factory = /** @class */ (function () {
    function LedgerLike__factory() {
    }
    LedgerLike__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    LedgerLike__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    LedgerLike__factory.abi = _abi;
    return LedgerLike__factory;
}());
exports.LedgerLike__factory = LedgerLike__factory;
