"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "",
                type: "bytes32"
            },
        ],
        name: "liquidatonPenalty",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "nonpayable",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "",
                type: "bytes32"
            },
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        name: "removeDebtFromLiquidation",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function"
    },
];
var LiquidationEngineLike__factory = /** @class */ (function () {
    function LiquidationEngineLike__factory() {
    }
    LiquidationEngineLike__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    LiquidationEngineLike__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    LiquidationEngineLike__factory.abi = _abi;
    return LiquidationEngineLike__factory;
}());
exports.LiquidationEngineLike__factory = LiquidationEngineLike__factory;
