"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "",
                type: "address"
            },
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
            {
                internalType: "bytes",
                name: "",
                type: "bytes"
            },
        ],
        name: "liquidationCallback",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function"
    },
];
var LiquidationAuctionCallee__factory = /** @class */ (function () {
    function LiquidationAuctionCallee__factory() {
    }
    LiquidationAuctionCallee__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    LiquidationAuctionCallee__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    LiquidationAuctionCallee__factory.abi = _abi;
    return LiquidationAuctionCallee__factory;
}());
exports.LiquidationAuctionCallee__factory = LiquidationAuctionCallee__factory;
