"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "getPrice",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
            {
                internalType: "bool",
                name: "",
                type: "bool"
            },
        ],
        stateMutability: "nonpayable",
        type: "function"
    },
];
var OracleLike__factory = /** @class */ (function () {
    function OracleLike__factory() {
    }
    OracleLike__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    OracleLike__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    OracleLike__factory.abi = _abi;
    return OracleLike__factory;
}());
exports.OracleLike__factory = OracleLike__factory;
