"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
exports.__esModule = true;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "getPrice",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
            {
                internalType: "bool",
                name: "",
                type: "bool"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "value",
                type: "uint256"
            },
        ],
        name: "setPrice",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function"
    },
    {
        inputs: [],
        name: "tokenPrice",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
var _bytecode = "0x608060405234801561001057600080fd5b506101c2806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80637ff9b5961461004657806391b7f5ed1461006457806398d5fdca14610080575b600080fd5b61004e61009f565b60405161005b919061011b565b60405180910390f35b61007e600480360381019061007991906100d4565b6100a5565b005b6100886100af565b604051610096929190610136565b60405180910390f35b60005481565b8060008190555050565b6000806000546001915091509091565b6000813590506100ce81610175565b92915050565b6000602082840312156100e657600080fd5b60006100f4848285016100bf565b91505092915050565b6101068161015f565b82525050565b6101158161016b565b82525050565b6000602082019050610130600083018461010c565b92915050565b600060408201905061014b600083018561010c565b61015860208301846100fd565b9392505050565b60008115159050919050565b6000819050919050565b61017e8161016b565b811461018957600080fd5b5056fea26469706673582212208483cc2c06512ba4b814a596e684c4adb5205efe72300d9770967bfd67b2c20364736f6c63430008040033";
var SimpleOracle__factory = /** @class */ (function (_super) {
    __extends(SimpleOracle__factory, _super);
    function SimpleOracle__factory(signer) {
        return _super.call(this, _abi, _bytecode, signer) || this;
    }
    SimpleOracle__factory.prototype.deploy = function (overrides) {
        return _super.prototype.deploy.call(this, overrides || {});
    };
    SimpleOracle__factory.prototype.getDeployTransaction = function (overrides) {
        return _super.prototype.getDeployTransaction.call(this, overrides || {});
    };
    SimpleOracle__factory.prototype.attach = function (address) {
        return _super.prototype.attach.call(this, address);
    };
    SimpleOracle__factory.prototype.connect = function (signer) {
        return _super.prototype.connect.call(this, signer);
    };
    SimpleOracle__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    SimpleOracle__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    SimpleOracle__factory.bytecode = _bytecode;
    SimpleOracle__factory.abi = _abi;
    return SimpleOracle__factory;
}(ethers_1.ContractFactory));
exports.SimpleOracle__factory = SimpleOracle__factory;
