"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "live",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "nonpayable",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        name: "shutdown",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "uint256",
                name: "debtToSell",
                type: "uint256"
            },
            {
                internalType: "uint256",
                name: "bidAmount",
                type: "uint256"
            },
        ],
        name: "startAuction",
        outputs: [
            {
                internalType: "uint256",
                name: "auctionId",
                type: "uint256"
            },
        ],
        stateMutability: "nonpayable",
        type: "function"
    },
];
var SurplusAuctionLike__factory = /** @class */ (function () {
    function SurplusAuctionLike__factory() {
    }
    SurplusAuctionLike__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    SurplusAuctionLike__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    SurplusAuctionLike__factory.abi = _abi;
    return SurplusAuctionLike__factory;
}());
exports.SurplusAuctionLike__factory = SurplusAuctionLike__factory;
