/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  DiscountCalculatorLike,
  DiscountCalculatorLikeInterface,
} from "../DiscountCalculatorLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "discountPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class DiscountCalculatorLike__factory {
  static readonly abi = _abi;
  static createInterface(): DiscountCalculatorLikeInterface {
    return new utils.Interface(_abi) as DiscountCalculatorLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DiscountCalculatorLike {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DiscountCalculatorLike;
  }
}
