/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { LedgerLike, LedgerLikeInterface } from "../LedgerLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "createUnbackedDebt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "transferDebt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class LedgerLike__factory {
  static readonly abi = _abi;
  static createInterface(): LedgerLikeInterface {
    return new utils.Interface(_abi) as LedgerLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LedgerLike {
    return new Contract(address, _abi, signerOrProvider) as LedgerLike;
  }
}
