/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { TokenLike, TokenLikeInterface } from "../TokenLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class TokenLike__factory {
  static readonly abi = _abi;
  static createInterface(): TokenLikeInterface {
    return new utils.Interface(_abi) as TokenLikeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenLike {
    return new Contract(address, _abi, signerOrProvider) as TokenLike;
  }
}
