/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IFeesEngine, IFeesEngineInterface } from "../IFeesEngine";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "collateralType",
        type: "bytes32",
      },
    ],
    name: "collateralTypes",
    outputs: [
      {
        internalType: "uint256",
        name: "stabilityFee",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastUpdated",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "globalStabilityFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IFeesEngine__factory {
  static readonly abi = _abi;
  static createInterface(): IFeesEngineInterface {
    return new utils.Interface(_abi) as IFeesEngineInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFeesEngine {
    return new Contract(address, _abi, signerOrProvider) as IFeesEngine;
  }
}
