/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISavingsAccount,
  ISavingsAccountInterface,
} from "../ISavingsAccount";

const _abi = [
  {
    inputs: [],
    name: "accumulatedRates",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "normalizedSavings",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "updateAccumulatedRate",
    outputs: [
      {
        internalType: "uint256",
        name: "nextAccumulatedRate",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "normalizedSavings",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISavingsAccount__factory {
  static readonly abi = _abi;
  static createInterface(): ISavingsAccountInterface {
    return new utils.Interface(_abi) as ISavingsAccountInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISavingsAccount {
    return new Contract(address, _abi, signerOrProvider) as ISavingsAccount;
  }
}
