/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IStablecoinJoin,
  IStablecoinJoinInterface,
} from "../IStablecoinJoin";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "position",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "stablecoin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "position",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IStablecoinJoin__factory {
  static readonly abi = _abi;
  static createInterface(): IStablecoinJoinInterface {
    return new utils.Interface(_abi) as IStablecoinJoinInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStablecoinJoin {
    return new Contract(address, _abi, signerOrProvider) as IStablecoinJoin;
  }
}
