service: bluejay
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30 # optional, in seconds, default is 6
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "ap-southeast-1"}
  environment:
    TABLE_NAME: bluejay-${opt:stage, "dev"}
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
functions:
  debug:
    handler: src/functionHandlers/debug/index.handler
    events:
      - http:
          path: /debug
          method: get
          cors: true
  updateOraclePrice:
    handler: src/functionHandlers/updateOraclePrice/index.handler
    events:
      - schedule: rate(30 minutes)
      - http:
          path: /updateOraclePrice
          method: get
          cors: true
  updateInfrastructure:
    handler: src/functionHandlers/updateInfrastructure/index.handler
    events:
      - schedule: rate(30 minutes)
      - http:
          path: /updateInfrastructure
          method: get
          cors: true
  reportSystemInfo:
    handler: src/functionHandlers/reportSystemInfo/index.handler
    events:
      - schedule: rate(30 minutes)
      - http:
          path: /reportSystemInfo
          method: get
          cors: true
custom:
  webpack:
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline
