name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup env
        run: cp packages/contracts/.env.example packages/contracts/.env

      - name: setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}">./packages/contracts/.npmrc

      - name: Configure CI Git User
        run: |
          git config --global user.name '@bluejay'
          git config --global user.email 'bluejay@users.noreply.github.com'

      - name: bootstrap project
        run: npx lerna bootstrap

      - name: build
        run: cd packages/contracts && npm run build

      - name: Publish package
        run: lerna publish --conventional-commits --yes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
